POST http://localhost:8080/update/counter/PauseTotalNs3/721200
Content-Type: text/plain

###
POST http://localhost:8080/update/gauge/
Content-Type: text/plain

###
GET http://localhost:8080/
Content-Type: text/plain

###
POST http://localhost:8080/value/
Content-Type: application/json

{
  "id": "PauseTotalNs",
  "type": "gauge"
}

###
GET http://localhost:8080/ping
Content-Type: text/plain

###
POST http://localhost:8080/update/counter/PauseTotalNs3/721200
Content-Type: text/plain
HashSHA256: 12365